name: "tests"
defaults:
  run:
    shell: bash
    working-directory: ./examples/simple
env:
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  ENV: testnut
  SSH_PUBLIC_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/aYdKsVZpBnLkvNA/AKLFHG+NBxUbPgCCeipedMQZqzv8hyQZAwyeVVD8w8yA/fFWmVBIu2Ww9UTtlknF7DmpFoXJGd+cOO5y7YOojS5OHVS4OJ35FR+oihW63o8Sv6N12HKKpDSLQQcUbxmHepkN6r/n2IIhdmQgTXKe06OxXYozsl3FsONtrTdI+5v114UzQx4zpG1bmDC9DRJO1s5FY062YjQXSMUDzdd9gP/o7yivunAGZjfEFcItVUjAWux53LIGjaNBBXUA5YtL08p40CxOX4k+Tz686SmbROP8ORCA5HOEYRfk5uuELhhS1+mipAJqgb40PMZlrcrpHUTqnanxxiGcXHVofzw7StaCI9ITdrMArmGIYD+gphSbW9HptF+6oBw8zB9n++T/vI+CvWf5ee+7MqbQPKlZgutS9QMhUnsCtNeuhLS9sNQO59KL4sEzpks3Cr+OlBj+Ib6pH3/S6HBp7mVoXnrQrW26f+O70QK3Y38XEZNQNJNjqG8= testnut-nutcorp"

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.3.0

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run Unit Tests
        working-directory: ./
        run: bats --report-formatter junit -o ./ tests/*.bats

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/report.xml'

  install-ssm-plugin:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install SSM Plugin
        run: make ssm-plugin

      - name: Show OS Debug Info
        run: make os.debug

      - name: Show ICMK Debug Info
        run: make icmk.debug

      - name: Show AWS Debug Info
        run: make aws.debug

  clean-install:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create Test directory
        run: mkdir -p ./test/clean-install

      - name: Clean Install
        working-directory: ./test/clean-install
        # Special directory that we use to test a clean install
        run: make init -f $(cat $GITHUB_WORKSPACE/init.mk > $(pwd)/init.mk && echo "$(pwd)/init.mk")

      - name: Init Examples
        working-directory: ./test/clean-install
        run: echo "y" | make examples.simple -f .infra/icmk/init.mk

      - name: Show OS Debug Info
        working-directory: ./test/clean-install
        run: make os.debug

      - name: Show ICMK Debug Info
        working-directory: ./test/clean-install
        run: make icmk.debug

      - name: Show AWS Debug Info
        working-directory: ./test/clean-install
        run: make aws.debug


  update-to-master:
    runs-on: ${{ matrix.os }}
    name: Update to master
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
    env:
      ICMK_VERSION: origin/master
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update ICMK
        run: make icmk.update

      - name: Show OS Debug Info
        run: make os.debug

      - name: Show ICMK Debug Info
        run: make icmk.debug

      - name: Show AWS Debug Info
        run: make aws.debug


  update-to-2_0_0:
    name: Update to 2.0.0
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11.0]
    env:
      ICMK_VERSION: tags/2.0.0
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      # TODO checkout older version, and test upgrade from one to another
      - name: Update ICMK
        run: make icmk.update

      - name: Show OS Debug Info
        run: make os.debug

      - name: Show ICMK Debug Info
        run: make icmk.debug

      - name: Show AWS Debug Info
        run: make aws.debug
